### ISSUE TITLE
capabilities should match appium style

### ISSUE THREAD

**Issue by jlipps** [YOU-i-Labs/appium-youiengine-driver#21]
Currently you can start a youi session using caps like these (according to the readme):

```
let defaultCaps = {
  app: 'path/to/your.app',
  platformName: 'YouiEngine',
  deviceName: 'iPhone 6'
  youiEngineAppPlatform: 'iOS'
  youiEngineAppAddress: 'localhost'
};
```

I didn't realize that youi is actually built on top of ios and android; I thought it was its own completely separate OS. Given that, the capabilities should actually look like this:

```
let defaultCaps = {
  app: 'path/to/your.app',
  platformName: 'iOS',
  deviceName: 'iPhone 6',
  automationName: 'YouiEngine',
  youiEngineAppAddress: 'localhost'
};
```

In other words, the platformName should be iOS or Android; what you are doing is adding a new kind of automation which is the YouiEngine.

(Also, and this is not as significant, but I'm guessing `youiEngineAppAddress` should have a default if it is most commonly going to be localhost)

**Comment by philgreenyouilabs** [comment]
> I didn't realize that youi is actually built on top of ios and android; I thought it was its own completely separate OS.

Slightly more nuanced - You.i Engine apps are native apps that run on iOS, Android and many other platforms. We do not use the native UI frameworks on those platforms (we are the UI framework) so from an application development perspective it's as if we were a completely separate OS. What this means is that the native (UI) automation frameworks on those platforms (UI Automation, UI Automator) are of no use with You.i Engine apps. The appium-ios-driver and appium-android-driver are of use to us to implement device (rather than UI) specific commands, we instantiate these in our driver. See https://github.com/YOU-i-Labs/appium-youiengine-driver/blob/master/lib/driver.js and https://github.com/YOU-i-Labs/appium-youiengine-driver/blob/master/README.md for the lists of commands that we say are 'proxied' by those platform drivers.

So in https://github.com/appium/appium/blob/master/lib/appium.js we could use `automationName` instead of `platformName` with a value of `youiengine` (after converstion to lowercase) and move the location to above the conditional checks for `platformName` being ios or android so that we can return our YouiEngineDriver:

```
  getDriverForCaps (caps) {
    // TODO if this logic ever becomes complex, should probably factor out
    // into its own file
    if (!caps.platformName || !_.isString(caps.platformName)) {
      throw new Error("You must include a platformName capability");
    }

    // we don't necessarily have an `automationName` capability,
    // but if we do and it is 'Selendroid', act on it
    if ((caps.automationName || '').toLowerCase() === 'selendroid') {
      return SelendroidDriver;
    }

    // could check for automationName == 'youiengine' here and return YouiEngineDriver

    if (caps.platformName.toLowerCase() === "fake") {
      return FakeDriver;
    }

    if (caps.platformName.toLowerCase() === 'android') {
      return AndroidDriver;
    }

    if (caps.platformName.toLowerCase() === 'ios') {
      return IosDriver;
    }

    if (caps.platformName.toLowerCase() === 'youiengine') {
      return YouiEngineDriver;
    }
```

The use of `platformName` being ios or android in the case of `automationName` being `youiengine` has other considerations:

1. We don't want any existing appium code that uses `platformName` to be invoked, we'd have to so some due diligence here. If we retain the use of our own variable (`youiEngineAppPlatform`) this ensures that we are the only user and there's no unwanted side effects.
2. In our driver we plan to support other `youiEngineAppPlatform`s that Appium doesn't support (game consoles, settops, desktops) so you would have to be ok with `platformName` taking on those other values (again, want to avoid any existing code that might grok on anything other than ios or android). In these cases we would not use the ios or android drivers for anything. The check for `platformName` having a value even though it is not required in this function in the case of `automationName` being `selendroid` might lend credence to the fact that `platformName` is used elsewhere, quick search shows this to be true.

**Comment by jlipps** [comment]
OK, thanks for that nuance! I must admit I was initially surprised to see you guys importing the Android and iOS drivers.

> We don't want any existing appium code that uses platformName to be invoked, we'd have to so some due diligence here. If we retain the use of our own variable (youiEngineAppPlatform) this ensures that we are the only user and there's no unwanted side effects.

Really the only place I'd worry about is in the `getDriverForCaps` section, which we are going to ensure works here. So I think it should be fine.

> In our driver we plan to support other youiEngineAppPlatforms that Appium doesn't support (game consoles, settops, desktops) so you would have to be ok with platformName taking on those other values.

Yes, that's what we'd want. If you're running apps on SamsungTV or something like that, then we would want that as the platformName.

> The check for platformName having a value even though it is not required in this function in the case of automationName being selendroid might lend credence to the fact that platformName is used elsewhere, quick search shows this to be true.

Maybe I'm not getting what you mean here, can you give some examples? Theoretically platformName is only used driver-internally, not at the main appium level. So as long as we can ensure that the youiengine-driver is selected in the right circumstances, that should be all we need to worry about.

> ` // could check for automationName == 'youiengine' here and return YouiEngineDriver (removing check for platformName below)`

👍

**Comment by philgreenyouilabs** [comment]
great thanks, we'll go forward implementing as per your recommendations.

**Comment by gitsaquib** [comment]
Can we set automationName in appium 1.5.3 UI

**Comment by TamimiGitHub** [comment]
Closing this issue as all recommendation has been implemented
